# Generated by Django 5.1.1 on 2024-11-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='record',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
