# Generated by Django 5.1.1 on 2024-11-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0002_team_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
