# Generated by Django 5.1.1 on 2024-12-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0003_team_last_updated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statteam',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='statteam',
            constraint=models.UniqueConstraint(fields=('team_id', 'category', 'stat_name'), name='unique_team_category_stat'),
        ),
    ]
