# Generated by Django 5.1.1 on 2025-01-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0005_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='season_type_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
