# Generated by Django 5.1.1 on 2025-01-31 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0006_alter_calendar_season_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_for_week', to='nfl.calendar'),
        ),
    ]
