# Generated by Django 4.2.20 on 2025-08-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0007_game_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='display_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='position_abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SeasonStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField()),
                ('season_type', models.CharField(default='Regular Season', max_length=20)),
                ('category_name', models.CharField(max_length=50)),
                ('stat_name', models.CharField(max_length=100)),
                ('stat_value', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('stat_display_value', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='nfl.athlete')),
            ],
            options={
                'unique_together': {('athlete', 'season_year', 'season_type', 'category_name', 'stat_name')},
            },
        ),
        migrations.CreateModel(
            name='GameStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=20)),
                ('game_date', models.DateField(null=True)),
                ('opponent', models.CharField(max_length=10, null=True)),
                ('category_name', models.CharField(max_length=50)),
                ('stat_name', models.CharField(max_length=100)),
                ('stat_value', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('stat_display_value', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='nfl.athlete')),
            ],
            options={
                'unique_together': {('athlete', 'event_id', 'category_name', 'stat_name')},
            },
        ),
    ]
