# Generated by Django 4.2.20 on 2026-08-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0009_game_scores_status_seasontype_statteam_season_calendar_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sub', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('picture', models.URLField(blank=True, default='')),
                ('sleeper_username', models.CharField(blank=True, default='', max_length=100)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
