# Generated by Django 4.2.20 on 2026-08-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0010_deskuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='depth_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='depth_slot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
