# Generated by Django 4.2.20 on 2026-09-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0011_athlete_depth_rank_athlete_depth_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_user_id', models.CharField(db_index=True, max_length=32)),
                ('username', models.CharField(max_length=100)),
                ('league_id', models.CharField(max_length=32)),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('sleeper_user_id', 'league_id')},
            },
        ),
    ]
